from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from fastapi.openapi.utils import get_openapi

from app.core.config import settings
from app.core.limiter import limiter
from app.core.middleware import APIVersionMiddleware, RequestLoggingMiddleware
from app.routers import gender_classifier, populators, profiles
from app.routers import auth as auth_router


def custom_openapi():
    """
    Custom function to generate the OpenAPI schema for the API.

    This function is used to customize the OpenAPI schema generated by FastAPI. It checks if the schema has already been generated and returns it if it exists. Otherwise, it calls the `get_openapi` function to generate the schema. It then adds a reusable header parameter named "X-API-Version" with a default value of "1" to every method in every route that starts with "/api/". The modified schema is stored in the `app.openapi_schema` attribute and returned.

    Returns:
        dict: The modified OpenAPI schema.

    """
    if app.openapi_schema:
        return app.openapi_schema

    openapi_schema = get_openapi(
        title=app.title,
        version=app.version,
        routes=app.routes,
    )

    # Define reusable header parameter
    api_version_header = {
        "name": "X-API-Version",
        "in": "header",
        "required": True,
        "schema": {"type": "string", "default": "1"},
    }

    # Inject into every /api/* route + every method
    for path, methods in openapi_schema["paths"].items():
        if path.startswith("/api/"):
            for method in methods.values():
                method.setdefault("parameters", [])
                # avoid duplicates
                if not any(
                    p.get("name") == "X-API-Version" for p in method["parameters"]
                ):
                    method["parameters"].append(api_version_header)

    app.openapi_schema = openapi_schema
    return app.openapi_schema


app = FastAPI(title=settings.PROJECT_NAME, version=settings.PROJECT_VERSION)
app.openapi = custom_openapi

# Schema is now managed by Alembic
# models.Base.metadata.create_all(bind=engine)


app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Custom middleware (order matters: added last = runs first)
app.add_middleware(APIVersionMiddleware)
app.add_middleware(RequestLoggingMiddleware)

app.include_router(auth_router.router, tags=["Auth"], prefix="/auth")
app.include_router(gender_classifier.router, tags=["Gender Classifier"], prefix="/api")
app.include_router(profiles.router, tags=["Profiles"], prefix="/api")
app.include_router(populators.router, tags=["Populators"], prefix="/api")


@app.exception_handler(HTTPException)
async def custom_http_exception_handler(request: Request, exc: HTTPException):
    """
    Custom exception handler for HTTPException.

    This function is used as an exception handler for HTTPException. It checks if the exception detail is a dictionary and if it contains a "status" key. If so, it returns a JSONResponse with the status code and the exception detail. Otherwise, it returns a JSONResponse with a generic error message.

    Args:
        request (Request): The incoming request.
        exc (HTTPException): The HTTPException instance.

    Returns:
        JSONResponse: The JSONResponse with the appropriate status code and content.

    """
    if isinstance(exc.detail, dict) and "status" in exc.detail:
        return JSONResponse(status_code=exc.status_code, content=exc.detail)
    return JSONResponse(
        status_code=exc.status_code,
        content={"status": "error", "message": str(exc.detail)},
    )


@app.get("/api/check")
async def check():
    """Check if the API is up and running."""
    return {"status": "ok"}
