"""add_indexes_to_profile_table

Revision ID: 58abf52992b5
Revises: 163bc7506f9e
Create Date: 2026-05-04 15:17:19.288182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58abf52992b5'
down_revision: Union[str, Sequence[str], None] = '163bc7506f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profile_age'), 'profile', ['age'], unique=False)
    op.create_index(op.f('ix_profile_age_group'), 'profile', ['age_group'], unique=False)
    op.create_index(op.f('ix_profile_country_id'), 'profile', ['country_id'], unique=False)
    op.create_index(op.f('ix_profile_gender'), 'profile', ['gender'], unique=False)
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_index(op.f('ix_profile_gender'), table_name='profile')
    op.drop_index(op.f('ix_profile_country_id'), table_name='profile')
    op.drop_index(op.f('ix_profile_age_group'), table_name='profile')
    op.drop_index(op.f('ix_profile_age'), table_name='profile')
    # ### end Alembic commands ###
